### Cadastro de usuario
POST http://localhost:3003/user/signup
Content-Type: application/json

{   
    "name": "Diego", 
    "email":"diego@email.com",
    "password":"123456",
    "role": "ADMIN"   
}

### Login do usuário
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email":"diego@email.com",
    "password":"123456"
}

### Registar banda no evento

POST http://localhost:3003/band/register
Authorization: {{login.response.body.token}}
Content-Type: application/json

{
    "name": "Bon Jovi",
    "genre": "Rock",
    "responsible": "Bon Jovi"
}

### Pega informações da Banda por ID ou Name

GET http://localhost:3003/band/getband
Authorization: {{login.response.body.token}}
Content-Type: application/json

{
    "id":"",
    "name":"Bon Jovi"
}
###
POST http://localhost:3003/show/register
Authorization: {{login.response.body.token}}
Content-Type: application/json

{
    "weekDay": "Saturday",
    "startTime": 15,
    "endTime": 23,
    "bandId":"eb3c75d1-d397-4415-a780-621b815a6b9d"
}

###
GET http://localhost:3003/show/getshow
Content-Type: application/json

{
    "day":"Sunday"
    
}