### Cadastro de usuario
POST http://localhost:3003/user/signup
Content-Type: application/json

{   
    "name": "Diego", 
    "email":"diego@email.com",
    "cpf": "12345678910",
    "password":"123456"
          
}

### Login do usuário
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email":"diego@email.com",
    "password":"123456"
}

### Registrar pagamento

POST http://localhost:3003/payment/register
Authorization: {{login.response.body.token}}
Content-Type: application/json

{
    "userId": "Bon Jovi",
    "clientId": "Rock",
    "amount": "Bon Jovi",
    "type":"",
    "cardHolderName":"",
    "cardNumber":"",
    "cardExpirationDate":"",
    "cardCvv":"",
}

### Pega informações da Banda por ID ou Name

GET http://localhost:3003/band/getband
Authorization: {{login.response.body.token}}
Content-Type: application/json

{
    "id":"",
    "name":"Bon Jovi"
}
