### Cadastro de usuario
POST http://localhost:3003/user/signup
Content-Type: application/json

{   
    "name": "Diego", 
    "email":"diego@email.com",
    "password":"123456",
    "role": "ADMIN"   
}

### Login do usuário
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email":"diego@email.com",
    "password":"123456"
}

