### Cadastrar Passeio
POST http://localhost:3003/dog/create
Content-Type: application/json

{   
    "data": "22/07/2022",
    "duração": "60",
    "latitude": "25º25'48''Sul",
    "longitude": "49º16'15'' Oeste",
    "pets": 3,
    "inicio": 15,
    "fim":1530
}

### Pegar Lista de Passeios
GET http://localhost:3003/dog/list
Content-Type: application/json

{
    "filtro": "sim"

}


