GET http://localhost:3003/recipes?title=torta&sort=&order=ASC&page=
Content-Type: application/json

####

GET http://localhost:3003/users
Content-Type: application/json

####

GET http://localhost:3003/users/name?name=ama
Content-Type: application/json

####

GET http://localhost:3003/users/type?type=Operati
Content-Type: application/json

####

GET http://localhost:3003/users/ordered/?order=name&?sort=
Content-Type: application/json


###

GET http://localhost:3003/users/paginate?page=4
Content-Type: application/json


###

GET http://localhost:3003/users/features/?name=&order=&sort=ASC&page=
Content-Type: application/json